<aside >  
	<h1 class="sidebar_topper"><span>Quick Contact Info:</span></h1>
	<dl>
		<dt>Phone:</dt><dd>865-584-5005</dd>
		<dt>Secure Fax:</dt><dd>865-588-9440</dd>
		<dt>Order Line:</dt><dd>800-545-8602</dd>
	</dl>
	<a href="contact_us_spc.php" title="Contact Us" tabindex="7">Contact Us Online</a>
	
	<h1><span>Order Information</span></h1>
	<p>Place your order<br>by phone or fax.</p>
	<p>We accept Visa, Discover, Mastercard,<br>American Express.</p>
	<p><a href="books.php#orderinfo">Click here</a> for additional order and shipping information.</p>
</aside>  