<section id="contactus_form">
	<div id="blurbs">
		<?php include('blurbs.php'); ?> 
	</div>
</section>
	
<section id="copyright">
	<address>Copyright&copy; 2011 <br>SPC Press</address>
</section>
	
<section id="designed_by">
	<a id="w3validator" href="http://jigsaw.w3.org/css-validator/check/referer"><h1>Site Design by:</h1></a>
	<a href="http://www.minotaurdesign.com" title="Site created by Minotaur Design" target="_blank"><h3>Minotaur Design</h3></a>
</section>
