<nav id="main">  
	<ul>
		<li id="home"><a href="index.php" title="SPC Press - Home page" tabindex="1">Home</a></li>
		<li id="books"><a href="books.php" title="Books" tabindex="2">Books</a></li>
		<li id="seminars"><a href="seminars.php" title="Seminars" tabindex="3">Seminars</a></li>
		<li id="other_products"><a href="other_products.php" title="Other Products" tabindex="4">Other Products</a></li>
		<li id="reading_room"><a href="reading_room.php" title="Reading Room" tabindex="5">Reading Room</a></li>
	</ul>
</nav>  