    <aside >  
        <h1 class="sidebar_topper"><span>Quick Contact Info:</span></h1>
        <dl>
            <dt>Phone:</dt><dd>865-584-5005</dd>
            <dt>Secure Fax:</dt><dd>865-588-9440</dd>
            <dt>Order Line:</dt><dd>800-545-8602</dd>
        </dl>
        <a href="contact_us_fw.php" title="Contact Us" tabindex="7">Contact Us Online</a>
        
      <h1><span>Seminar Info</span></h1>
 		<p>To schedule a seminar for your organization <a href="contact_us_fw.php" title="Contact Fran Wheeler">contact Fran Wheeler.</a></p>
		
      <h1><span>Upcoming Seminars:</span></h1>
       <ul>
          	<li class="seminar_title"><a href="seminar_understanding_statistical_process_control.php">Understanding<br>Statistical<br> Process<br> Control</a></li>
            <li>September 19-22, 2011</li>
            <li>Knoxville, Tennessee</li>
            <li>Price: $1595.</li>
            <li>Includes all books, breakfast buffets, <br>and lunches.</li>
         </ul>
  </aside>  